### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by tromp** [xenoncat/cuckoo_pow#1]
Congratulations on winning my bounty, xenoncat!
See https://github.com/tromp/cuckoo/issues/18 for your reward and choice of payout.
Further documentation is still welcome...

**Comment by tromp** [comment]
Could you also provide a cuckoo20 to see what remains of the speedup at low memory settings?
Thanks!
(btw, could you use an anonymous email account to correspond directly with me?)

**Comment by xenoncat** [comment]
Added cuckoo20.
You can send private message to xenoncat in forum.z.cash
